export const ROUTES = {
  login: '/login',
  register: '/register',
  createTenant: '/criar-empresa',
  adminTenants: '/admin/empresas',
  adminLogs: '/admin/logs',
  dashboard: '/',
  freights: '/fretes',
  freightCreate: '/fretes/novo',
  freightDetail: (id: number | string) => `/fretes/${id}`,
  freightEdit: (id: number | string) => `/fretes/${id}/editar`,
  drivers: '/motoristas',
  users: '/usuarios',
  fleet: '/frota',
  tenant: '/empresa',
  calendar: '/calendario',
  driverProfile: '/meu-perfil',
  support: '/suporte',
  reports: '/relatorios',
} as const
